### ISSUE TITLE
Arquillian Integration tests are not working

### ISSUE THREAD

**Issue by miPlodder** [arquillian/arquillian-extension-jacoco#102]
##### Issue Overview

Arquillian Integration tests are not working

##### Expected Behaviour

Integration tests should pass

##### Current Behaviour

Integration tests fails

##### Steps To Reproduce
1. Execute `$ mvn -pl com.test:test verify -P jacoco,integration-test`
2. It's fails with below logs
```
java.lang.RuntimeException: Could not run @AfterSuite
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.AdaptorManager.shutdown(AdaptorManager.java:53)
	at test.ear//org.jboss.arquillian.junit.AdaptorManagerWithNotifier$1.testRunFinished(AdaptorManagerWithNotifier.java:29)
	at test-SNAPSHOT.ear//org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
	at test-SNAPSHOT.ear//org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at test-SNAPSHOT.ear//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.container.JUnitTestRunner.execute(JUnitTestRunner.java:61)
	at test-SNAPSHOT.ear//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
	at test-SNAPSHOT-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
	at test-SNAPSHOT-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at o.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
...
org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.7.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No command response within timeout of 30000 ms.
	at test-SNAPSHOT.ear-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletCommandService.execute(ServletCommandService.java:54)
	at test-SNAPSHOT.ear//org.jboss.arquillian.extension.jacoco.container.ShutdownCoverageData.writeCoverageData(ShutdownCoverageData.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at test-SNAPSHOT.ear//org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at test-SNAPSHOT.ear//org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.afterSuite(EventTestRunnerAdaptor.java:75)
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.AdaptorManager.shutdown(AdaptorManager.java:44)
	... 90 more
```

##### Additional Information

arquillian-extension-jacoco:1.0.0
jacoco-maven-plugin: 0.8.10

```
<details>
 <summary>$mvn --version</summary>
 Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/maven
Java version: 17.0.6, vendor: Azul Systems, Inc., runtime: /opt/jdk-17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.83.1.el7.x86_64", arch: "amd64", family: "unix"
</details>
```

Apache Maven  (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/maven
Java version: 
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.83.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by miPlodder** [comment]
Any inputs on why we are get above error would be really helpful?

**Comment by chengfang** [comment]
@miPlodder what is the exact command you used? `Execute $ mvn -pl com.test verify -P jacoco,integration-test` doesn't seem right.

Have you tried with jdk 8?

**Comment by miPlodder** [comment]
I trimmed the command as I don't want to exposure the package structure. Corrected it in PR desc also,

> `mvn -pl com.test:test verify -P jacoco,integration-test`

This command is correct, else would have gotten a completely different error.

**Comment by miPlodder** [comment]
<h3>Additional details:</h3>

When we ran only ran `integration-test` profile activated (`mvn -pl com.test:test verify -P integration-test`), it works.
Whereas when ran only with `jacoco` profile activated (`mvn -pl com.test:test verify -P jacoco,integration-test`), it FAILS.

<h3>Recently, we added few dependency to our pom.xml file which are </h3>

- commons-fileupload:commons-fileupload
- commons-io:commons-io

- org.springframework:spring-context-support
- org.springframework:spring-webmvc</artifactId>
- org.springframework.security:spring-security-web
- org.springframework.security:spring-security-config

- org.aspectj:aspectjtools
- org.aspectj:aspectjrt
- org.aspectj:aspectjweaver
- org.hibernate:hibernate-validator
- org.springframework:spring-test
- org.glassfish:javax.el


<h3>Container Logs</h3>

[container_logs.txt](https://github.com/arquillian/arquillian-extension-jacoco/files/11497919/container_logs.txt)

**Comment by miPlodder** [comment]
https://stackoverflow.com/questions/52899241/org-aspectj-apache-bcel-classfile-classformatexception-invalid-byte-tag-in-cons/58976575#58976575
Uplifting to latest version of AspectJ fixes it.
