### ISSUE TITLE
org.jboss.shrinkwrap.api.exporter.ArchiveExportException: Failed to write asset to output: /WEB-INF/classes/...

### ISSUE THREAD

**Issue by leccyril** [arquillian/arquillian-extension-jacoco#32]
##### Issue Overview

when jacoco-maven-plugin is used with jacoco-arquillian 1.0.09alpha extension , arquillian archive not created with above error.

I configure 2 projects with same configuration but more little project and it works. If i comment the jacoco Arquillian extension war archive is created and IT test are executed but no coverage could be made on

##### Expected Behaviour
arquillian war archive created, deployed and IT test executed then code coverage
##### Current Behaviour

Caused by: java.lang.RuntimeException: Could not instrument Asset org.jboss.shrinkwrap.api.asset.ClassLoaderAsset@6ea020d4
	at org.jboss.arquillian.extension.jacoco.client.instrumentation.InstrumentedAsset.openStream(InstrumentedAsset.java:60)
	at org.jboss.shrinkwrap.impl.base.exporter.AbstractOnDemandInputStream.read(AbstractOnDemandInputStream.java:130)
	... 128 more
Caused by: java.io.IOException: Error while instrumenting class arquillian.
	at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:111)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:130)
	at org.jboss.arquillian.extension.jacoco.client.instrumentation.InstrumentedAsset.openStream(InstrumentedAsset.java:55)
	... 129 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information

java 8 jacoco-maven-plugin 0.7.8 last arquillian BOM version (all last version lib)

For long outputs such as stacktraces please use HTML5 `<details>`

```

**Comment by leccyril** [comment]
finally after spent 2 days to search how to fix issue, it appears that asm-debug lib was omitted because other libs already imported an older asm-debug.. look at dependency hierarchy in eclipse with pom.xml
